### ISSUE TITLE
throw - why m () instead of m a ?

### ISSUE THREAD

**Issue by miguel-negrao** [turion/has-transformers#1]
The function throw forces the value inside the monad to be ():

```Haskell
throw :: HasExcept e m => e -> m ()
throw e = liftH $ ExceptT $ return $ Left e
```

In [mtl](https://hackage.haskell.org/package/mtl-2.2.2/docs/Control-Monad-Except.html), [transformers](https://hackage.haskell.org/package/transformers-0.6.0.4/docs/Control-Monad-Trans-Except.html) and also in eolc that type is left as arbitrary:

```
-- mtl
throwError :: e -> m a 
-- transformers
throwE :: Monad m => e -> ExceptT e m a 
```
I think I have already encountered situations where having () is less flexible.

**Comment by turion** [comment]
You're absolutely right, the type should be arbitrary. No idea why I made it `()`. PR welcome.
